apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: goweb-app
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /
            backend:
              serviceName: goweb-app
              servicePort: 8080