apiVersion: v1
kind: Service
metadata:
  name: goweb-app
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.matchLabels }}
  selector:
        {{- toYaml .Values.matchLabels| nindent 4 }}
      {{- end }}